"""add user_medication table

Revision ID: 2d37545a0c5a
Revises: a455c5091f8b
Create Date: 2025-08-17 11:00:18.260018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d37545a0c5a'
down_revision = 'a455c5091f8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_medication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('medication_name', sa.String(length=120), nullable=False),
    sa.Column('dosage', sa.String(length=60), nullable=True),
    sa.Column('frequency', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_medication', schema=None) as batch_op:
        batch_op.create_index('ix_user_med_medication', ['user_id', 'medication_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_medication_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_medication', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_medication_user_id'))
        batch_op.drop_index('ix_user_med_medication')

    op.drop_table('user_medication')
    # ### end Alembic commands ###
