"""add lifestyle table

Revision ID: 40c59d65caf9
Revises: c5de3a438bfa
Create Date: 2025-08-17 10:51:03.769501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40c59d65caf9'
down_revision = 'c5de3a438bfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lifestyle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('smoking_status', sa.String(length=30), nullable=True),
    sa.Column('alcohol_consumption', sa.String(length=30), nullable=True),
    sa.Column('exercise_frequency', sa.String(length=30), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lifestyle')
    # ### end Alembic commands ###
