"""add monitoring table

Revision ID: 6de5de7e6cc7
Revises: 40c59d65caf9
Create Date: 2025-08-17 10:52:33.598742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6de5de7e6cc7'
down_revision = '40c59d65caf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('glucose_frequency', sa.String(length=30), nullable=True),
    sa.Column('latest_hba1c_percent', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('uses_cgm', sa.Boolean(), nullable=True),
    sa.Column('frequent_hypoglycemia', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monitoring')
    # ### end Alembic commands ###
