"""add medical_history table

Revision ID: a455c5091f8b
Revises: ae0b32e9e15c
Create Date: 2025-08-17 10:57:41.347970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a455c5091f8b'
down_revision = 'ae0b32e9e15c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('family_history_heart_disease', sa.Boolean(), nullable=True),
    sa.Column('currently_on_insulin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medical_history')
    # ### end Alembic commands ###
