"""add medical_reminder table

Revision ID: adc99629bac0
Revises: 2d37545a0c5a
Create Date: 2025-08-17 11:02:05.379240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adc99629bac0'
down_revision = '2d37545a0c5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_reminder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('medication_name', sa.String(length=120), nullable=False),
    sa.Column('dosage', sa.String(length=60), nullable=True),
    sa.Column('frequency', sa.String(length=60), nullable=True),
    sa.Column('time_of_day', sa.Time(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_reminder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_reminder_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_reminder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_reminder_user_id'))

    op.drop_table('medical_reminder')
    # ### end Alembic commands ###
