"""add user_condition table

Revision ID: ae0b32e9e15c
Revises: babd79ff3f8a
Create Date: 2025-08-17 10:55:34.427317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae0b32e9e15c'
down_revision = 'babd79ff3f8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_condition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.Column('other', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['condition_id'], ['condition.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'condition_id', name='uq_user_condition')
    )
    with op.batch_alter_table('user_condition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_condition_condition_id'), ['condition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_condition_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_condition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_condition_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_condition_condition_id'))

    op.drop_table('user_condition')
    # ### end Alembic commands ###
