"""add verified_at column to users

Revision ID: d32f4d3a7e3b
Revises: 0e8af1c5b51c
Create Date: 2025-08-17 10:19:09.522860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd32f4d3a7e3b'
down_revision = '0e8af1c5b51c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verified_at')

    # ### end Alembic commands ###
