"""resync after fixing missing revision

Revision ID: f1b1f6ef57f8
Revises: f7c11e9ab7cc
Create Date: 2025-09-01 13:51:23.522706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b1f6ef57f8'
down_revision = 'f7c11e9ab7cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_assessments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_password_reset_sent_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_password_reset_sent_at')

    op.create_table('weekly_assessments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('week_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('glucose_frequency', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('range_compliance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('energy_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sleep_quality', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('medication_adherence', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('concerns', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('overall_feeling', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('weekly_assessments_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('weekly_assessments_pkey')),
    sa.UniqueConstraint('user_id', 'week_date', name=op.f('uq_weekly_assessments_user_week'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
